### PR TITLE
Added typescript definitions

### PR DESCRIPTION
**Pull request by dotBeFoRE**

### CODE REVIEW

**Comment by nkbt** [comment]
Thank you for the PR

I don't work with TS and do not have any plans or capability of supporting this language. There is a 3rd party `@types/react-copy-to-clipboard`

**Comment by dotBeFoRE** [comment]
Adding a index.d.ts to your project also allows VSCode's Intellisense to give better suggestions. So it doesn't only help TS developers, but it also helps normal JS developers.

Also `@types/react-copy-to-clipboard` doesn't work 😬.

**Comment by nkbt** [comment]
Why not pr to @types one instead?

I am also not using vscode and webstorm has great support for js without having ts in it. 

I am actually quite serious about not having any ts in my personal repos. I’ve made a mistake of letting ts in one or two repos and had heaps of issues with it later as it needs all the updates when code updates, or ts compiler updates or many many other things. I am not willing to support it and initial committers we not supporting it either.

All this work I do in my spare time and the only thing that makes me do this work - I enjoy it. I absolutely do not enjoy TS, sorry.

**Comment by namoscato** [comment]
Thanks for this great component, @nkbt!

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48888 fixes `@types/react-copy-to-clipboard` so you don't have to mess with it in here.

**Comment by nkbt** [comment]
Great, thank you

**Pull request closed without merging**
