### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gilesbradshaw**
fixed import

### CODE REVIEW

**Comment by nkbt** [comment]
Either named and default import should be working fine. See https://github.com/nkbt/react-copy-to-clipboard/blob/master/src/index.js

PS: ignore CircleCI check, this project needs some updates to not fail in CI

**Comment by gilesbradshaw** [comment]
ah ok - I am using typescript and @types/react-copy-to-clipboard and it kicks out named import - the problem must be there.  Looking at it I see the types are for version 4.2..  Presumably you don't maintain @types/copy-to-clip-board?

**Comment by gilesbradshaw** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25414#issuecomment-421186234

**Comment by nkbt** [comment]
No, I’m not using any kind of typed js

**Comment by gilesbradshaw** [comment]
ah yes I mean the problem is in the definitelytyped stuff which you aren't the maintainer of - sorry to waste your time :)

**Pull request closed without merging**
