### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by soroushchehresa**

### CODE REVIEW

**Comment by nkbt** [comment]
Not sure why this change... Everything in current readme works fine.

**Comment by soroushchehresa** [comment]
@nkbt 
`{CopyToClipboard}` has an error on TypeScript and other edits just are best practices and you can see them on [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript)

**Comment by nkbt** [comment]
1. Types definitions are incomplete. Either import works fine. Please make a PR to that repo (I do not support ts)
2. Reformatting makes readme not the same style as actual code in repo and would not pass my eslint config that is in this repo

**Comment by soroushchehresa** [comment]
@nkbt All right, so I close this PR. Thanks for your quick response.

**Pull request closed without merging**
