### PR TITLE
Fix import specifier in docs since it is the default export

### PR DESCRIPTION
**Pull request by TejasQ**

### CODE REVIEW

**Comment by nkbt** [comment]
Both are valid, an default export was added later as an alternative, so changing this in readme may imply it is a breaking change, but it is not really.

I'd rather leave it as is or add default export as extra alternative way.

**Comment by TejasQ** [comment]
> Both are valid.

I'm not convinced. Especially since the default export was added later, it's a little strange that the original version as specified in the README gives me errors.

image

**Comment by nkbt** [comment]
https://github.com/nkbt/react-copy-to-clipboard/blob/master/src/index.js

The problem you are showing is with your TS config, not library.

**Comment by TejasQ** [comment]
Actually, the problem is with the type definitions exported for this library from DefinitelyTyped in the `@types/react-copy-to-clipboard` library. I've commented about this on [an issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25414#issuecomment-421186234) over at their repository.

**Comment by nkbt** [comment]
I see. I an not supporting ts defs, you can probably pr to defs repo to sort this out

**Comment by TejasQ** [comment]
Thank you, @nkbt. I wish you the best. 🙂

**Comment by applemate** [comment]
is this resolved yet? I got the same issue in 2021

**Comment by nkbt** [comment]
> is this resolved yet? I got the same issue in 2021

I am not using TS and I am not the author of @types/react-copy-to-clipboard type declarations - it is a completely independent package.

This in not an issue of this package. It supports both named and default exports. It is a problem of type declarations someone put out there.

**Pull request closed without merging**
