### PR TITLE
Transformer func prop

### PR DESCRIPTION
**Pull request by oridr**
The transformer is an optional prop, that modifies the content before it is copied to the clipboard.

Examples of use:

- clearing markdown
- adding quotes
- trimming spaces
- changing line break symbols

### CODE REVIEW

**Comment by nkbt** [comment]
Why not do it in the app component, and not library? I don't think there is any reason to add extra function to the lib, that can be trivially added in the app instead.

Slightly updated example from this PR:
```jsx
<CopyToClipboard
  onCopy={text => this.onCopy(this.transform(text))}
  text={this.state.value}>
  <button>Copy to clipboard with button</button>
</CopyToClipboard>
```

**Comment by oridr** [comment]
I want to transform the data that is going to the clipboard, so that the clipboard content won't be the same as the content in the input.

The `onCopy` hook happens after the copy action.  The transformation will not effect the data in the clipboard. 

Moving the `onCopy` before the copy action, will create other problems:
- I can't store the modified elements in the state because it's async. In addition, I don't want to change the data that appears in the source.
- If I use a property of the object, or a variable, I'll have two copies of the state, albeit a little bit different.
- The `onCopy` will be called before the action itself, so it can't be used to remove the text from the state, for example.

**Comment by nkbt** [comment]
Can you transform text that comes into Clipboard then?

```jsx
<CopyToClipboard
  onCopy={this.onCopy}
  text={this.transform(this.state.value)}>
  <button>Copy to clipboard with button</button>
</CopyToClipboard>
```

**Comment by oridr** [comment]
I've thought about that, and it works. However, in a controlled component, with a large amount of data, running a complicated transformation on every change might hurt performance, and make typing sluggish.

I can debounce the transform method, but it will still do unnecessary work, whenever you stop typing.

I can also understand your point of view - the component is simple, does it's work well, and you don't want to over complicate it. However, I think that if you've got a post copy hook, a pre copy hook (maybe under another name than transformer), that can tap and change the copied data would be in the spirit of the component.

**Comment by nkbt** [comment]
Sorry, but this feature is out of scope for this library.

You can easily create component in your app, that wraps `CopyToClipboard` with that one extra transform. 


That's the only thing you need to do and then use it everywhere in your app.
```jsx
import React from 'react';
export class TrimCopy extends React.Component {
  transform = text => `"${text.trim()}"`;
  render() {
    const {value, ...rest} = this.props;
    return <CopyToClipboard text={this.transform(value)} {...rest} />;
  }
}
```

**Comment by oridr** [comment]
Thank you for your time

**Pull request closed without merging**
